services:
  rivenbot:
    container_name: rivenbot
    image: ${DOCKER_IMAGE_NAME}
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb
      - loki
    secrets:
      - mongo_username
      - mongo_password
      - discord_bot_token
      - discord_bot_public_key
      - discord_application_id
      - discord_client_id
      - discord_client_secret
      - bungie_api_key
      - bungie_client_id
      - bungie_client_secret
  redis:
    container_name: redis
    hostname: redis
    image: "redis:7.0.11"
    ports:
      - "6379:6379"
  mongodb:
    container_name: mongodb
    hostname: mongo
    image: "mongo:7.0.3"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
      MONGO_INITDB_DATABASE: riven_of_a_thousand_servers
    secrets:
      - "mongo_username"
      - "mongo_password"
  loki:
    container_name: loki
    hostname: loki
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
  grafana:
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER__FILE: /run/secrets/grafana_admin_username
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    secrets:
      - "grafana_admin_username"
      - "grafana_admin_password"
    volumes:
      - ./grafana/custom-config.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana
      - ./grafana/ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml

secrets:
  mongo_username:
    environment: "MONGO_DB_ROOT_USERNAME"
  mongo_password:
    environment: "MONGO_DB_ROOT_PASSWORD"
  discord_bot_token:
    environment: "DISCORD_BOT_TOKEN"
  discord_bot_public_key:
    environment: "DISCORD_BOT_PUBLIC_KEY"
  discord_application_id:
    environment: "DISCORD_APPLICATION_ID"
  discord_client_id:
    environment: "DISCORD_CLIENT_ID"
  discord_client_secret:
    environment: "DISCORD_CLIENT_SECRET"
  bungie_api_key:
    environment: "BUNGIE_API_KEY"
  bungie_client_id:
    environment: "BUNGIE_CLIENT_ID"
  bungie_client_secret:
    environment: "BUNGIE_CLIENT_SECRET"
  grafana_admin_username:
    environment: "GRAFANA_ADMIN_USERNAME"
  grafana_admin_password:
    environment: "GRAFANA_ADMIN_PASSWORD"

volumes:
  grafana-storage: { }