version: 0.1.0-SNAPSHOT
services:
  bot-application:
    image: "deahtstroke/destiny2bot:0.0.1-SNAPSHOT"
    ports:
      - "443:443"
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
