services:
  riven-of-a-thousand-servers:
    container_name: rivenbot
    image: ${DOCKER_IMAGE_NAME}
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb
    secrets:
      - mongo_username
      - mongo_password
      - discord_bot_token
      - discord_bot_public_key
      - discord_application_id
      - discord_client_id
      - discord_client_secret
      - bungie_api_key
      - bungie_client_id
      - bungie_client_secret
  redis:
    container_name: redis
    hostname: redis
    image: "redis:7.0.11"
    ports:
      - "6379:6379"
  mongodb:
    container_name: mongodb
    hostname: mongo
    image: "mongo:7.0.3"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
      MONGO_INITDB_DATABASE: riven_of_a_thousand_servers
    secrets:
      - "mongo_username"
      - "mongo_password"
  loki:
    container_name: loki
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  grafana:
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"

secrets:
  mongo_username:
    environment: "MONGO_DB_ROOT_USERNAME"
  mongo_password:
    environment: "MONGO_DB_ROOT_PASSWORD"
  discord_bot_token:
    environment: "DISCORD_BOT_TOKEN"
  discord_bot_public_key:
    environment: "DISCORD_BOT_PUBLIC_KEY"
  discord_application_id:
    environment: "DISCORD_APPLICATION_ID"
  discord_client_id:
    environment: "DISCORD_CLIENT_ID"
  discord_client_secret:
    environment: "DISCORD_CLIENT_SECRET"
  bungie_api_key:
    environment: "BUNGIE_API_KEY"
  bungie_client_id:
    environment: "BUNGIE_CLIENT_ID"
  bungie_client_secret:
    environment: "BUNGIE_CLIENT_SECRET"