spring:
  data:
    redis:
      port: 6379
      host: localhost
    mongodb:
      port: 27017
      host: localhost
      username: root
      password: password
      authentication-database: admin
      database: d2armory

bungie:
  api:
    callbackUrl: ${application.callback.url}/bungie/callback

discord:
  api:
    callbackUrl: ${application.callback.url}/discord/callback

server:
  port: 8080
  ssl:
    enabled: false

application:
  callback:
    # Replace with your own callback url masking port 8080 to run locally
    url: https://5ba3-2600-1700-4390-a930-a0c5-3cf0-b839-bdcc.ngrok-free.app

