spring:
  data:
    redis:
      host: localhost
    mongodb:
      host: localhost

application:
  callback:
    # Replace with your own callback url masking port 8080 to run locally
    url: https://c797-2600-1700-4390-a930-95a3-1de8-fb35-181.ngrok-free.app