spring:
  data:
    redis:
      port: 6379
  security:
    oauth2:
      client:
        provider:
          bungieOAuth2Client:
            authorization-uri: https://www.bungie.net/en/oauth/authorize
            token-uri: https://www.bungie.net/platform/app/oauth/token/
        registration:
          bungieOAuth2Client:
            provider: bungieOAuth2Client
            client-id: ${BUNGIE_CLIENT_ID}
            client-secret: ${BUNGIE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost:443/login/oauth2/code/bungieOAuth2Client

server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-alias: tomcat
    key-store-password: password

bungie:
  api:
    key: ${BUNGIE_API_KEY}
    baseUrl: https://www.bungie.net/Platform
    currentUserMembershipUrl: ${bungie.api.baseUrl}/User/GetMembershipsForCurrentUser/
    profileDataUrl: ${bungie.api.baseUrl}/Destiny2/{membershipType}/Profile/{destinyMembershipId}/
    manifestEntityDefinitionUrl: ${bungie.api.baseUrl}/Destiny2/Manifest/{entityType}/{hashIdentifier}/
    entityToClassMap:
      STAT_DEFINITION: StatDto