spring:
  data:
    redis:
      host: redis
    mongodb:
      host: mongo

application:
  inviteLink: https://discord.com/oauth2/authorize?client_id=1177030727678820362
  callback:
    url: https://rivenbot.app