spring:
  threads:
    virtual:
      enabled: true
  data:
    redis:
      port: 6379
      host: redis
  security:
    oauth2:
      client:
        provider:
          bungieOAuth2Client:
            authorization-uri: https://www.bungie.net/en/oauth/authorize
            token-uri: https://www.bungie.net/platform/app/oauth/token/
        registration:
          bungieOAuth2Client:
            provider: bungieOAuth2Client
            client-id: ${BUNGIE_CLIENT_ID}
            client-secret: ${BUNGIE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: https://d2discord.app/login/oauth2/code/bungieOAuth2Client

server:
  port: 443
  ssl:
    key-store: keystore.pfx
    key-store-type: PKCS12
    key-store-password: ${KEYSTORE_PASSWORD}

bungie:
  api:
    key: ${BUNGIE_API_KEY}
    baseUrl: https://www.bungie.net/Platform
    currentUserMembershipUrl: ${bungie.api.baseUrl}/User/GetMembershipsForCurrentUser/
    profileDataUrl: ${bungie.api.baseUrl}/Destiny2/{membershipType}/Profile/{destinyMembershipId}/
    manifestEntityDefinitionUrl: ${bungie.api.baseUrl}/Destiny2/Manifest/{entityType}/{hashIdentifier}/

discord:
  api:
    version: 10
    baseUrl: https://discord.com/api/v${discord.api.version}
    botToken: ${DISCORD_BOT_TOKEN}
    permissionsInteger: 137439217728
