spring:
  threads:
    virtual:
      enabled: true
  data:
    redis:
      port: 6379
      host: redis
    mongodb:
      port: 27017
      host: mongo
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      authentication-database: admin
      database: destiny2bot

server:
  port: 443
  ssl:
    key-store: keystore.pfx
    key-store-type: PKCS12
    key-store-password: ${KEYSTORE_PASSWORD}

bungie:
  api:
    key: ${BUNGIE_API_KEY}
    clientSecret: ${BUNGIE_CLIENT_SECRET}
    clientId: ${BUNGIE_CLIENT_ID}
    baseUrl: https://www.bungie.net/Platform
    authorizationUrl: https://www.bungie.net/en/oauth/authorize
    tokenUrl: https://www.bungie.net/platform/app/oauth/token/
    callbackUrl: ${application.callback.url}/bungie/callback
    currentUserMembershipUrl: ${bungie.api.baseUrl}/User/GetMembershipsForCurrentUser/
    profileDataUrl: ${bungie.api.baseUrl}/Destiny2/{membershipType}/Profile/{destinyMembershipId}/
    manifestEntityDefinitionUrl: ${bungie.api.baseUrl}/Destiny2/Manifest/{entityType}/{hashIdentifier}/

discord:
  api:
    version: 10
    baseUrl: https://discord.com/api/v${discord.api.version}
    tokenUrl: https://discord.com/api/oauth2/token
    callbackUrl: ${application.callback.url}/discord/callback
    authorizationUrl: https://discord.com/oauth2/authorize
    botToken: ${DISCORD_BOT_TOKEN}
    botPublicKey: ${DISCORD_BOT_PUBLIC_KEY}
    permissionsInteger: 137439217728
    clientId: ${DISCORD_CLIENT_ID}
    clientSecret: ${DISCORD_CLIENT_SECRET}
    scopes: identify

application:
  callback:
    url: https://d2discord.app
