spring:
  data:
    redis:
      port: 6379
      host: localhost
    mongodb:
      port: 27017
      host: localhost
      username: root
      password: password
      authentication-database: admin
      database: d2armory
  security:
    oauth2:
      client:
        provider:
          discordOAuth2Client:
            authorization-uri:
            token-uri:
          bungieOAuth2Client:
            authorization-uri: https://www.bungie.net/en/oauth/authorize
            token-uri: https://www.bungie.net/platform/app/oauth/token/
        registration:
          bungieOAuth2Client:
            provider: bungieOAuth2Client
            client-id: ${BUNGIE_CLIENT_ID}
            client-secret: ${BUNGIE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost:443/login/oauth2/code/bungieOAuth2Client
          discordOAuth2Client:
            provider: bungieOAuth2Client
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost:443/discord/callback

bungie:
  api:
    callbackUrl: https://localhost:443/bungie/callback

discord:
  api:
    callbackUrl: https://localhost:443/discord/callback

server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-alias: tomcat
    key-store-password: password

