name: Deployment to EC2

on:
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run the Gradle Build
        run: ./gradlew clean build

      - name: Archive build JARs
        uses: actions/upload-artifact@v3
        with:
          name: uploaded-artifact
          path: |
            /build/libs/destiny2bot-**.jar \
            !/build/libs/destiny2bot-**-plain.jar

      - name: Set Project name and version as environment variables
        run: |
          echo "PROJECT_VERSION=$(./gradlew -q version)" >> $GITHUB_ENV \
          echo "PROJECT_NAME=$(./gradlew -q projectName)" >> $GITHUB_ENV

  dockerize-and-upload:
    needs: build-and-package
    
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug image name
        run: echo "${{ secrets.DOCKERHUB_USERNAME }}/ ${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}"

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:  
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}
