name: Deployment to EC2

env:
  DOCKERHUB_USERNAME: deahtstroke

on:
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: List the files
        run: ls
        
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run the Gradle Build
        run: ./gradlew clean build

      - name: Set Project name and version as environment variables
        run: |
          echo "${{ env.DOCKERHUB_USERNAME}}/$(./gradlew -q projectName):$(./gradlew -q version)" > imageName.txt
          cat imageName.txt
          
      - name: Upload Docker Image Name as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-name
          path: |
            imageName.txt
            !build/libs/destiny2bot-*-plain.jar
            build/libs/destiny2bot-*.jar

  dockerize-and-upload:
    needs: build-and-package
    
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Image Name File
        uses: actions/download-artifact@v3
        with:
          name: docker-image-name

      - name: List artifact files
        run: ls -R

      - name: Set variable with docker image name
        run: |
          content=$(cat ./imageName.txt)
          echo "DOCKER_IMAGE_NAME=$content" >> $GITHUB_ENV
        shell: bash

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:  
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          build-args: JAR_FILE=./build/libs/destiny2bot-*.jar
          
