name: Gradle Build
run-name: ${{ github.actor }} Gradle Build
on: [push]
jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run the Gradle Build
        run: ./gradlew build