name: Gradle Build
run-name: ${{ github.actor }} Gradle Build
on: [push]
jobs:
  gradle-build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run the Gradle Build
        run: ./gradlew build