name: Gradle Build
run-name: ${{ github.actor }} Gradle Build
on: [push]
jobs:
  gradle-build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Run the Gradle Package Task
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: -b ci.gradle package